version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    entrypoint: sh
    command: -c 'mkdir -p /data/carplbucket && minio server --console-address ":9001" /data'
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /home/minio/hdd:/data
    environment:
      MINIO_REGION: ap-south-1
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: secret-key
